mainProject/accounts/urls.py
from django.urls import path
from .views import user_create_form, verify, profile, add_additional_info, delete_account,edit_profile,login_view,custom_logout,request_password_reset,password_reset_confirm

urlpatterns = [
    path('verify/<str:key>/', verify, name='verify'),
    path('register/', user_create_form, name='user_create_form'),
    path('profile/<int:user_id>/', profile, name='profile'),
    path('add_additional_info/', add_additional_info, name='add_additional_info'),
    path('delete/<int:user_id>/', delete_account, name='delete_account'),
    path('edit/<int:user_id>/', edit_profile, name='edit_profile'),
    path('login/', login_view, name='login'),
    path('logout/<int:user_id>/', custom_logout, name='custom_logout'),
    path('password_reset/', request_password_reset, name='password_reset'),  # Password reset request view
    path('password_reset_confirm/<str:token>/', password_reset_confirm, name='password_reset_confirm'),  # Password reset confirmation view
]

mainProject/mainProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainProject/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError

class User(AbstractUser):
    username = models.CharField(max_length=150, unique=True)  # Ensure username is unique
    email = models.EmailField(unique=True)  # Ensure email is unique
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/images', null=True, blank=True)
    facebook_profile = models.URLField(max_length=200, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    is_activated = models.BooleanField(default=False)
    activation_key = models.CharField(max_length=64, blank=True)
    reset_token = models.CharField(max_length=100, blank=True, null=True)

    # Add related_name attributes to resolve clashes
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        related_name='user_groups'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name='user_permissions_set'
    )

    def save(self, *args, **kwargs):
        # Ensure that the username and email are not empty
        if not self.username:
            raise ValidationError("Username cannot be empty.")
        if not self.email:
            raise ValidationError("Email cannot be empty.")
        # Perform additional actions before saving the user
        super().save(*args, **kwargs)

    @property
    def profile_picture_url(self):
        if self.profile_picture:
            return self.profile_picture.url
        return '/path/to/default/profile/picture.jpg'

mainProject/accounts/forms.py
from django import forms
from django.contrib.auth.hashers import make_password
from .models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'confirm_password', 'phone_number',
                  'profile_picture']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password:
            if password != confirm_password:
                self.add_error('confirm_password', "Passwords do not match.")
            if len(password) < 5:
                self.add_error('password', "Password must be at least 5 characters long.")
        else:
            self.add_error('password', "Password field is required.")

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        if password:
            user.password = make_password(password)  # Hash the password
        if commit:
            user.save()
        return user

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if len(first_name) < 2:
            raise forms.ValidationError("First name must be at least 2 characters long.")
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if len(last_name) < 2:
            raise forms.ValidationError("Last name must be at least 2 characters long.")
        return last_name
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        allowed_endings = ['.com', '.gmail', '.edu']
        if not any(email.endswith(ending) for ending in allowed_endings):
            raise forms.ValidationError("Please enter a valid email address.")
        return email
    
    def clean_profile_picture(self):
        profile_picture = self.cleaned_data.get('profile_picture')
    
        if not profile_picture:
            return "users/images/1_.jpg"  # This should be the relative path to the default image
    
        return profile_picture

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
    
        if phone_number is None:
            raise forms.ValidationError("Phone number is required.")
    
        phone_input = ''.join(filter(str.isdigit, phone_number))
    
        if len(phone_input) >= 10:
            if len(phone_input) == 10:
                phone_number_with_prefix = "+20" + phone_input
            else:
                phone_number_with_prefix = "+" + phone_input
        else:
            raise forms.ValidationError("Invalid phone number format.")
    
        return phone_number_with_prefix



class AdditionalInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['birth_date', 'country', 'facebook_profile']

    birth_date = forms.DateField(
        label='Birth Date',
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
    )
    country = forms.CharField(
        label='Country',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    facebook_profile = forms.URLField(
        label='Facebook Profile',
        required=False,
        widget=forms.URLInput(attrs={'class': 'form-control'})
    )


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")

        if email and password:
            user = User.objects.filter(email=email).first()
            if user and password:
                self.user = user
            else:
                raise forms.ValidationError("Invalid email or password.")
        return cleaned_data

mainProject/accounts/views.py
import pytz
from django.core.mail import send_mail
from django.urls import reverse
from datetime import datetime, timedelta
import uuid
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse, JsonResponse,HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.core.mail import send_mail
from .forms import UserForm, AdditionalInfoForm,LoginForm
from .models import User
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import LoginForm
import logging



class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'

def verify(request, key):
    user = User.objects.filter(activation_key=key).first()
    if user:
        timestamp = int(key.split('_')[-1])
        activation_time = datetime.fromtimestamp(timestamp).replace(tzinfo=pytz.utc)
        now = datetime.now(pytz.utc)
        if now - activation_time > timedelta(hours=24):
            return render(request, 'accounts/activation_expired.html')
        user.is_activated = True
        user.save()
        return render(request, 'accounts/account_activated.html', {'user': user})
    else:
        return HttpResponse("Invalid activation key.")

def activateEmail(request, user):
    timestamp = int(timezone.now().timestamp())
    activation_key = str(uuid.uuid4()) + '_' + str(timestamp)
    user.activation_key = activation_key
    user.save()
    activation_link = request.build_absolute_uri(reverse('verify', kwargs={'key': activation_key}))
    send_mail(
        'Activate Your Account',
        f'Dear {user.first_name}, please click the following link to activate your account: {activation_link}',
        'sender@example.com',
        [user.email],
        fail_silently=False,
    )
    messages.success(request, f"An activation email has been sent to {user.email}.")

def user_create_form(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])
            user.confirm_password = make_password(form.cleaned_data['confirm_password'])
            user.is_activated = False
            image = request.FILES.get("profile_picture")
            if image:
                user.profile_picture = image
            else:
                user.profile_picture = "users/images/1_.jpg"
            user.save()
            activateEmail(request, user)
            return render(request, 'accounts/activation_email_sent.html', {'email': user.email})
    else:
        form = UserForm()
    return render(request, 'accounts/register.html', {'form': form})

logger = logging.getLogger(__name__)

def add_additional_info(request):
    if request.method == 'POST':
        form = AdditionalInfoForm(request.POST)
        if form.is_valid():
            user_id = request.POST.get('user_id')
            if user_id:
                user = get_object_or_404(User, pk=user_id)
                user.birth_date = form.cleaned_data['birth_date']
                user.country = form.cleaned_data['country']
                user.facebook_profile = form.cleaned_data['facebook_profile']
                user.save()
                return redirect('profile', user_id=user.id)
            else:
                return HttpResponse("User ID is missing.")
    else:
        form = AdditionalInfoForm()
    return render(request, 'accounts/additional_info_form.html', {'form': form})

def delete_account(request):
    if request.method == 'POST':
        try:
            user_id = request.POST.get('user_id')
            user = User.objects.get(pk=user_id)
            user.delete()
            return render(request, 'accounts/register.html')
        except User.DoesNotExist:
            return HttpResponse("User does not exist.")
    return HttpResponse("Invalid request.")



def edit_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            profile_picture = request.FILES.get('profile_picture')
            if profile_picture:
                user.profile_picture = profile_picture
            form.save()
            messages.success(request, "Profile updated successfully.")
    else:
        form = UserForm(instance=user)
    
    return render(request, 'accounts/edit.html', {'form': form, 'user': user})



def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.user
            user.is_active = True
            user.save() 

            if user.is_activated:
                login(request, user)
                return redirect('profile', user_id=user.id)
            else:
                return render(request, 'accounts/not_activated.html', {'email': user.email})
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


def custom_logout(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.is_active= False
    user.save()
    return redirect('login')


def profile(request, user_id):
    if request.user.is_authenticated:
        return redirect('profile', user_id=request.user.id)

    user = get_object_or_404(User, pk=user_id)

    if user.is_active:
        if user.is_activated:
            form = AdditionalInfoForm(instance=user)
            return render(request, 'accounts/profile.html', {'form': form, 'user': user})
        else:
            return render(request, 'accounts/not_activated.html')
    else:
        return redirect('login')


def generate_reset_token(user):
    timestamp = int(timezone.now().timestamp())
    reset_token = str(uuid.uuid4()) + '_' + str(timestamp)
    user.reset_token = reset_token
    user.save()
    return reset_token

def request_password_reset(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.filter(email=email).first()
        if user:
            reset_token = generate_reset_token(user)
            reset_link = request.build_absolute_uri(reverse('password_reset_confirm', kwargs={'token': reset_token}))
            send_mail(
                'Password Reset',
                f'Click the following link to reset your password: {reset_link}',
                'sender@example.com',
                [user.email],
                fail_silently=False,
            )
            messages.success(request, "Password reset link sent to your email.")
            return redirect('login')
        else:
            messages.error(request, "User with this email does not exist.")
    return render(request, 'registration/password_reset_request.html')


def password_reset_confirm(request, token):
    user = User.objects.filter(reset_token=token).first()
    if user:
        timestamp = int(token.split('_')[-1])
        reset_time = datetime.fromtimestamp(timestamp).replace(tzinfo=pytz.utc)
        now = datetime.now(pytz.utc)
        if now - reset_time > timedelta(hours=24):
            messages.error(request, "Password reset link has expired.")
            return redirect('login')
        else:
            if request.method == 'POST':
                new_password = request.POST.get('new_password')
                confirm_password = request.POST.get('confirm_password')
                if new_password == confirm_password:
                    user.set_password(new_password)
                    user.reset_token = None
                    user.save()
                    # messages.success(request, "Password reset successfully.")
                    return redirect('login')
                else:
                    messages.error(request, "Passwords do not match.")
    else:
        messages.error(request, "Invalid or expired reset link.")
    return render(request, 'registration/password_reset_confirm.html')




def delete_account(request, user_id):
    if request.method == 'POST':
        try:
            user_id = request.POST.get('user_id')
            password = request.POST.get('password')
            
            user = get_object_or_404(User, pk=user_id)
            if user.check_password(password):
                user.delete()
                return redirect('user_create_form') 
            else:
                return JsonResponse({'success': False, 'message': 'Incorrect password'})
        except User.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'User does not exist.'})
        

mainProject/accounts/templates/accounts/account_activated.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Account Activated</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'mainApp/css/activate.css' %}" rel="stylesheet">
    <style>
        .frist {
            background-image: url("{% static 'mainApp/img/icon_right.jpg' %}");
        }

        a {
            color: white !important;
            text-decoration: none;
        }
        a:hover{
            text-decoration: none;
        }
    </style>
</head>

<body class="container">
    <div class="frist">

    </div>
    <div class="sec">
        <h1>Your account has been activated!</h1>
        <p>Your account has been successfully activated. You can now log in to your account.</p>
        <span class="arrow">
            <a href="{% url 'profile' user.id %}">your profile</a>
        </span>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

mainProject/accounts/templates/accounts/activation_email_sent.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Activated</title>
                    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'mainApp/css/activate.css' %}" rel="stylesheet">
    <style>
    .frist {
        background-image: url("{% static 'mainApp/img/email.jpg' %}");
    }  
    </style> 
</head>
<body class="container">
    <div class="frist"></div>
    <div class="sec">
        <h1>Activation Email Sent</h1>
        <p>An activation email has been sent to 
            <a href="mailto:{{ email }}" class="email">{{ email }}</a>.
            <br/>
            Please check your email inbox and follow the instructions to activate your account.
        </p>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

mainProject/accounts/templates/accounts/activation_expired.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account Activated</title>
                    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'mainApp/css/activate.css' %}" rel="stylesheet">
    <style>
    .frist {
        background-image: url("{% static 'mainApp/img/expire.jpg' %}");
    }  
    </style>    
</head>
<body class="container">
    <div class="frist" >

    </div>
    <div class="sec">
    <h1>confirmation link is expire!</h1>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

mainProject/accounts/templates/accounts/additional_info_form.html
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title></title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .modal-backdrop {
            display: none;
        }

        .modal-content {
            box-shadow: 0 0 70px rgba(0, 0, 0, 0.3);
        }


        .form-group {
    position: relative;
    margin-bottom: 20px;
    width: 80%;
    margin-right: 2%;
}

.form-group:last-child {
    margin-right: 0;
}

.form-group label {
    position: absolute;
    left: 10px;
    top: 5px;
    color: #777;
    transition: all 0.3s ease;
    pointer-events: none;
    font-size: 15px;
}

.form-group input {
    width: 100%;
    padding: 30px 10px 20px 10px;
    border: 2px solid #149954;
    border-radius: 4px;
    font-size: 13px; 

}

.form-group:focus-within label {
    top: -10px;
    left: 10px;
    background-color: white;
    padding: 0 5px;
    font-size: 12px;
    color: #149954;
    border-color: #149954;
}

.btn-primary{
 background-color: #149954;
 border-color: transparent;
}

.btn-primary:hover{
 background-color: #034c1d;
 border-color: transparent;
}
    </style>
</head>

<body>
    <div class="modal fade" id="additionalInfoModal" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Additional Information</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="additionalInfoForm" method="POST" enctype="multipart/form-data" action="{% url 'add_additional_info' %}">                        {% csrf_token %}
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        <div class="form-group">
                            <label for="id_birth_date">Birth Date</label>
                            <!-- Render form errors -->
                            {% if form.birth_date.errors %}
                            {% for error in form.birth_date.errors %}
                            <div class="error-message">{{ error }}</div>
                            {% endfor %}
                            {% endif %}
                            {{ form.birth_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_country">Country</label>
                            <!-- Render form errors -->
                            {% if form.country.errors %}
                            {% for error in form.country.errors %}
                            <div class="error-message">{{ error }}</div>
                            {% endfor %}
                            {% endif %}
                            {{ form.country }}
                        </div>
                        <div class="form-group">
                            <label for="id_facebook_profile">Facebook Profile</label>
                            <!-- Render form errors -->
                            {% if form.facebook_profile.errors %}
                            {% for error in form.facebook_profile.errors %}
                            <div class="error-message">{{ error }}</div>
                            {% endfor %}
                            {% endif %}
                            {{ form.facebook_profile }}
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    var $j = jQuery.noConflict();
    $j(document).ready(function() {
        // Your jQuery code using $j instead of $
    });
</script>

</body>

</html>

mainProject/accounts/templates/accounts/not_activated.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Activated</title>
                    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'mainApp/css/activate.css' %}" rel="stylesheet">
    <style>
    .frist {
        background-image: url("{% static 'mainApp/img/email.jpg' %}");
    }  
    </style> 
</head>
<body class="container">
    <div class="frist"></div>
    <div class="sec">
        <h1>Your Account is not activated</h1>
        <p>You Should active your account through the 
            activation 
            link
            that has been sent to your email
            Please check your email inbox and follow the
            instructions to activate your account.
            <br/>
            Or if you didn't have an account should register first through this link
            <br/>
            <span class="arrow">
                <a href="{% url 'user_create_form' %}">Register</a>
            </span>
        </p>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

mainProject/accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
        rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'mainApp/css/register.css' %}" rel="stylesheet">
    <style>
        body {
            background-image: url("{% static 'mainApp/img/back.jpg' %}");
            height: 100vh;
        }

        .frist {
            background-image: url("{% static 'mainApp/img/mosque.jpg' %}");
            height: 38vh;
        }
        .sec{
            height: 60vh;
        }
    </style>
</head>

<body>
    <div class="frist">
        <h2>Join Us</h2>
    </div>
    <div class="sec">
        <form method="post" action="{% url 'user_create_form' %}" enctype="multipart/form-data" class="mt-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                {{ form.username }}
                {% for error in form.username.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="id_first_name">First Name</label>
                {{ form.first_name }}
                {% for error in form.first_name.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="id_last_name">Last Name</label>
                {{ form.last_name }}
                {% for error in form.last_name.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="id_email">Email</label>
                {{ form.email }}
                {% for error in form.email.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="id_password">Password</label>
                    {{form.password}}
                {% for error in form.password.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="id_confirm_password">Confirm Password</label>
                {{ form.confirm_password }}
                {% for error in form.confirm_password.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            
            <div class="form-group">
                <div class="input-group">
                    {{ form.phone_number }}
                    <div class="input-group-prepend">
                        <span class="input-group-text">+20</span>
                    </div>
                </div>
                {% for error in form.phone_number.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            
            
            <div class="form-group">
                {{ form.profile_picture }}
                {% for error in form.profile_picture.errors %}
                <div class="error-message">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-submit-group">
                <button type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('input, textarea, select').forEach(function(input) {
                input.removeAttribute('required');
            });

    
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>